stackabletech/zookeeper-operator

- operator/src/lib.rs
So far we'd always try to delete an "excess" Pod even though it might already have a deletion timestamp.
This would lead to (harmless but annoying) 404 errors in the logs.
> Fixes #17 by checking if a Pod is already deleted before attempting another deletion

- Cargo.lock
- crd/Cargo.toml
- operator/Cargo.toml
This is mainly an update of operator-rs so we can benefit from the fixes to list_pods.
> Dependency updates

- crd/src/lib.rs
- crd/zookeepercluster.crd.yaml
- examples/simple-zookeepercluster.yaml
- operator/src/lib.rs
- server/src/main.rs
I hope I caught all references
> Rename stackable.de to stackable.tech

- .gitignore
- Cargo.lock
- README.adoc
- crd/src/lib.rs
- deploy/config-spec/properties.yaml
- deploy/crd/zookeepercluster.crd.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/commandline_args.adoc
- docs/modules/ROOT/pages/configuration.adoc
- docs/modules/ROOT/pages/usage.adoc
- examples/simple-zookeepercluster.yaml
- operator/src/lib.rs
- server/Cargo.toml
- server/packaging/buildrpm.sh
- server/packaging/copy_assets.py
- server/packaging/rpm/SOURCES/stackable-zookeeper-operator-server-VERSION/usr/lib/systemd/system/stackable-zookeeper-operator-server.service
- server/packaging/rpm/SPECS/stackable-zookeeper-operator-server.spec
- server/src/main.rs
- Added metrics port to CR
- Added ENV variable for javaagent to start jmx exporter
Also fixes #147
> Enable monitoring

- .github/dependabot.yml
- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- crd/Cargo.toml
- deny.toml
- operator/Cargo.toml
- server/Cargo.toml
This PR is part of a chain of PRs across all our projects to make them as consistent as possible in preparation for our first release.
Things it can contain (not all might be applicable to all repositories):
- Cargo.toml
- Add `repository` key
- Set version properly
- Sort keys
- deny.toml consistency
- Pull request template
- Github CI consistency (e.g. rustdoc)
- cargo update
- Dependabot does not ignore stackable components anymore
- Adds changelog & readme
- Correct license
> Project updates

- docs/modules/ROOT/pages/usage.adoc
> Adds brief warning to the docs about #176 with a workaround

- CHANGELOG.md
- Cargo.lock
- deploy/crd/zookeepercluster.crd.yaml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/crd/src/util.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/stackable-zookeeper-operator.rs
- rust/operator/Cargo.toml
- rust/operator/src/lib.rs
> Changed to kube-rs 0.60 and k8s-openapi features v1.22.

- CHANGELOG.md
- Cargo.lock
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.4.0. DO NOT SQUASH MERGE!
> Release 0.4.0

- examples/simple-zookeepercluster.yaml
- rust/operator-binary/Cargo.toml
> Bugfix: add command CRDS to packages.

- .github/workflows/publish_dev_artifacts.yml
Fix whitespace issue in dev artifact publishing.
> Fix whitespacing in helm release

- CHANGELOG.md
- Cargo.lock
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.5.0. DO NOT SQUASH MERGE!
> Release 0.5.0

- Cargo.lock
- deploy/crd/zookeepercluster.crd.yaml
- rust/crd/src/lib.rs
> Remove version 3.4.14. Added 3.6.3 and 3.7.0

- rust/crd/src/lib.rs
- rust/operator-binary/src/zk_controller.rs
> Use upstreamed RoleGroupRef from operator-rs

- CHANGELOG.md
- Cargo.lock
- deploy/helm/zookeeper-operator/Chart.yaml
- deploy/manifests/configmap.yaml
- deploy/manifests/deployment.yaml
- deploy/manifests/serviceaccount.yaml
- deploy/manifests/tests/test.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
> Release 0.7.0

- deploy/helm/zookeeper-operator/crds/crds.yaml
- deploy/manifests/crds.yaml
> Update Helm CRDs

- docs/modules/ROOT/pages/installation.adoc
I think there docker docs were overseen when the rework was made. I've updated them.
> Updated docker docs

- Cargo.lock
- README.adoc
- README.md
- rust/operator-binary/src/zk_controller.rs
- README update
- Dependency updates
- Rustdoc fixes
> Various changes

- CHANGELOG.md
- rust/operator-binary/src/zk_controller.rs
run as group 0 for release 23.4.1
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> run as group 0 for release 23.4.1

- CHANGELOG.md
- Cargo.lock
- deploy/helm/zookeeper-operator/crds/crds.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-authentication.yaml
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-encryption.yaml
- docs/modules/zookeeper/pages/config_properties.adoc
- examples/simple-zookeeper-tls-cluster.yaml
- rust/crd/Cargo.toml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/main.rs
- rust/operator-binary/src/zk_controller.rs
- rust/operator-binary/src/znode_controller.rs
- tests/templates/kuttl/cluster-operation/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/30-pause-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/40-restart-zookeeper.yaml.j2
- tests/templates/kuttl/delete-rolegroup/00-install-zookeeper.yaml.j2
- tests/templates/kuttl/delete-rolegroup/01-remove-secondary.yaml.j2
- tests/templates/kuttl/logging/01-install-zookeeper.yaml.j2
- tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/znode/00-install-zookeeper.yaml.j2
- tests/test-definition.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Default stackableVersion to operator version

- Cargo.lock
- Cargo.toml
- deploy/helm/zookeeper-operator/crds/crds.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Switch to workspace dependencies

- docs/modules/zookeeper/pages/usage_guide/resource_configuration.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Mention StorageClass

- deploy/helm/zookeeper-operator/crds/crds.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
- docs/modules/zookeeper/pages/usage_guide/listenerclass.adoc
- docs/modules/zookeeper/partials/nav.adoc
- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add ListenerClass docs

- docs/modules/zookeeper/pages/getting_started/installation.adoc
- docs/modules/zookeeper/pages/index.adoc
- docs/modules/zookeeper/pages/usage_guide/authentication.adoc
- docs/modules/zookeeper/pages/usage_guide/encryption.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
> docs: Update references

- rust/operator-binary/src/zk_controller.rs
- rust/operator-binary/src/znode_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
> refactor: Use operator-rs Duration

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/zookeeper-operator/crds/crds.yaml
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-authentication.yaml
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-encryption.yaml
- docs/modules/zookeeper/pages/config_properties.adoc
- docs/modules/zookeeper/pages/discovery.adoc
- docs/modules/zookeeper/pages/index.adoc
- docs/modules/zookeeper/pages/usage_guide/configuration_environment_overrides.adoc
- docs/modules/zookeeper/pages/znodes.adoc
- docs/modules/zookeeper/partials/deprecated-versions.adoc
- docs/modules/zookeeper/partials/removed-versions.adoc
- docs/modules/zookeeper/partials/supported-versions.adoc
- examples/simple-zookeeper-tls-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/zk_controller.rs
- rust/operator-binary/src/znode_controller.rs
- tests/templates/kuttl/logging/00-install-zookeeper-vector-aggregator.yaml
- tests/test-definition.yaml
- added removed and deprecated versions docs
- bumped zk version to 3.8.3
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add new version 3.8.3

- Cargo.lock
- Cargo.toml
- rust/crd/src/authentication.rs
- rust/crd/src/lib.rs
- rust/crd/src/security.rs
- rust/crd/src/tls.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/main.rs
- rust/operator-binary/src/product_logging.rs
- rust/operator-binary/src/utils.rs
- rust/operator-binary/src/zk_controller.rs
- rust/operator-binary/src/znode_controller.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- CHANGELOG.md
- deploy/helm/zookeeper-operator/crds/crds.yaml
- docs/modules/zookeeper/pages/usage_guide/log_aggregation.adoc
- rust/crd/src/lib.rs
- rust/operator-binary/src/product_logging.rs
- tests/templates/kuttl/cluster-operation/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/delete-rolegroup/00-install-zookeeper.yaml.j2
- tests/templates/kuttl/logging/01-install-zookeeper.yaml.j2
- tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/znode/00-install-zookeeper.yaml.j2
This is a **breaking** CRD change.
fixes #736 
- docs updated
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix!: inconsistency in CRD for logging configuration fixed

- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Template zookeeper version in getting started command

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/zookeeper-operator/crds/crds.yaml
- rust/crd/src/authentication.rs
- rust/crd/src/lib.rs
- rust/crd/src/tls.rs
- rust/operator-binary/src/main.rs
Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Better CRD docs

- tests/templates/kuttl/cluster-operation/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/30-pause-zookeeper.yaml.j2
- tests/templates/kuttl/cluster-operation/40-restart-zookeeper.yaml.j2
- tests/templates/kuttl/delete-rolegroup/00-install-zookeeper.yaml.j2
- tests/templates/kuttl/delete-rolegroup/01-remove-secondary.yaml.j2
- tests/templates/kuttl/logging/01-install-zookeeper.yaml.j2
- tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/znode/00-install-zookeeper.yaml.j2
Part of https://github.com/stackabletech/issues/issues/481
> feat(test): pull policy IfNotPresent

- CHANGELOG.md
- deploy/helm/zookeeper-operator/templates/_helpers.tpl
- deploy/helm/zookeeper-operator/templates/deployment.yaml
- deploy/helm/zookeeper-operator/templates/roles.yaml
- deploy/helm/zookeeper-operator/values.yaml
Part of https://github.com/stackabletech/issues/issues/188 and https://github.com/stackabletech/issues/issues/501
> feat: Add support for labels in `values.yaml` file

- deploy/helm/zookeeper-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add Stackable vendor label to default values.yaml

- CHANGELOG.md
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-authentication.yaml
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-encryption.yaml
- docs/modules/zookeeper/pages/index.adoc
- docs/modules/zookeeper/pages/reference/discovery.adoc
- docs/modules/zookeeper/pages/usage_guide/configuration_environment_overrides.adoc
- docs/modules/zookeeper/pages/znodes.adoc
- docs/modules/zookeeper/partials/supported-versions.adoc
- examples/simple-zookeeper-tls-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/zk_controller.rs
- tests/test-definition.yaml
- added 3.9.1
- removed 3.8.1
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Support zookeeper 3.9.1

- CHANGELOG.md
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-authentication.yaml
- docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-encryption.yaml
- docs/modules/zookeeper/pages/reference/discovery.adoc
- docs/modules/zookeeper/pages/usage_guide/configuration_environment_overrides.adoc
- docs/modules/zookeeper/pages/znodes.adoc
- docs/modules/zookeeper/partials/supported-versions.adoc
- examples/simple-zookeeper-tls-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/zk_controller.rs
- tests/test-definition.yaml
Replace zookeeper `3.9.1` with `3.9.2`.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: add zookeeper 3.9.2

- rust/operator-binary/src/zk_controller.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test: Improve configOverrides test

- docs/modules/zookeeper/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: update supported versions text

- docs/modules/zookeeper/pages/usage_guide/authentication.adoc
- docs/modules/zookeeper/pages/usage_guide/log_aggregation.adoc
- docs/modules/zookeeper/pages/usage_guide/using_multiple_role_groups.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: fix links

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- tests/templates/kuttl/logging/11-copy-prepared-logs.yaml
- tests/templates/kuttl/logging/prepared-logs.log4j.xml
- tests/templates/kuttl/logging/zookeeper-vector-aggregator-values.yaml.j2
Add prepared logs to the logging test containing invalid log events
Tests stackabletech/operator-rs#802
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add prepared logs to the logging test

- CHANGELOG.md
- docs/modules/zookeeper/partials/supported-versions.adoc
- tests/test-definition.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Remove support for Zookeeper 3.8.3

- docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml
> docs(getting-started): Update zookeeper.yaml template

- docs/modules/zookeeper/pages/usage_guide/log_aggregation.adoc
- docs/modules/zookeeper/pages/usage_guide/resource_configuration.adoc
> docs: remove home module from refs (stackabletech/documentation#637)

- tests/templates/kuttl/logging/05-install-zookeeper-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> chore: Bump Vector to 0.40.0

- deploy/helm/zookeeper-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(helm): use the same scc as olm

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/smoke/11-assert.yaml
Part of: https://github.com/stackabletech/issues/issues/548
:green_circle: Test
```shell
$ ./scripts/run-tests --test-suite smoke-latest
...
--- PASS: kuttl (43.39s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-false_use-client-auth-tls-false_openshift-false (43.38s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(test): smoke testing env and config overrides

- tests/templates/kuttl/logging/05-install-zookeeper-vector-aggregator.yaml
Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Upgrade the Vector aggregator in the logging tests

- Cargo.lock
- Cargo.toml
- deploy/helm/zookeeper-operator/crds/crds.yaml
- rust/crd/src/authentication.rs
- rust/crd/src/security.rs
- rust/crd/src/tls.rs
- rust/operator-binary/src/zk_controller.rs
part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump op-rs

- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/install_output.txt
Part of https://github.com/stackabletech/issues/issues/647.
> docs: Update release in getting_started

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/zookeeper-operator/Chart.yaml
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> release: 24.11.1-rc2

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/zookeeper-operator/templates/roles.yaml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/main.rs
- rust/operator-binary/src/zk_controller.rs
- rust/operator-binary/src/znode_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```
> chore: Update to operator-rs 0.84.0

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/crd/mod.rs
Follow up to https://github.com/stackabletech/zookeeper-operator/pull/917
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: add struct version to versioned macro status field

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
```
--- PASS: kuttl (388.52s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/znode_zookeeper-latest-3.9.3_openshift-false (44.01s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-false_use-client-auth-tls-false_openshift-false (70.11s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-true_use-client-auth-tls-true_openshift-false (126.15s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.3_use-server-tls-true_use-client-auth-tls-true_openshift-false (126.40s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-true_use-client-auth-tls-false_openshift-false (74.02s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-false_use-client-auth-tls-true_openshift-false (71.69s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.3_use-server-tls-false_use-cli …
```
> chore: Bump stackable-operator to 0.87.5

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/zookeeper-operator/Chart.yaml
- deploy/helm/zookeeper-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/product_logging.rs
- rust/operator-binary/src/zk_controller.rs
- Inject vector aggregator address into the vector config using the env var `VECTOR_AGGREGATOR_ADDRESS`.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Inject vector aggregator address as env into vector config

- tests/templates/kuttl/logging/05-install-zookeeper-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
> chore: bump vector chart to 0.43.0

- CHANGELOG.md
- deploy/helm/zookeeper-operator/templates/roles.yaml
> fix: Backport Add RBAC permission to patch events

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/zookeeper-operator/Chart.yaml
- docs/modules/zookeeper/examples/getting_started/code/getting_started.sh
- docs/modules/zookeeper/examples/getting_started/code/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.7.0
