stackabletech/zookeeper-operator

Cargo.lock, NOTICE, crd/Cargo.toml, crd/src/error.rs, crd/src/lib.rs, crd/src/util.rs, operator/src/lib.rs
Zookeeper acts as backing store for many other services. Operators for these services will have to retrieve connection information from a Zookeeper object.
This PR adds a first version of function to retrieve the connection string from the api-server.
Functionality was added to the CRD crate, as this is the one that is most commonly used by other operators already.
=> Added first version of code to retrieve zookeeper connection string

.github/workflows/build_artifacts.yml
Adds build action to publish artifacts to the dev repo. Also changed nightly versions to be published to the dev repo instead of the nightly repo.
For PRs the version number is changed before building by adding the pr number as a suffix.
Suppress publishing of artifacts for runs that are triggered externally (dependabot mostly) as these do not have access to the necessary secret for deploying artifacts.
=> Adds a conditional action to build and push rpm and apt artifacts for pull requests to the dev repositories in nexus.

Cargo.lock, crd/Cargo.toml, crd/src/lib.rs, operator/Cargo.toml
- kube-runtime as a dependency wasn't needed
- SemVer crate updated to 1.0.3 which required a minor code change
=> Update semver to 1.0.3 & remove kube-runtime

.github/workflows/build_artifacts.yml
We started using the action-has-permission action in our workflows a while ago in order to avoid unnecessary job failures, when dependabot created pull requests that don't have access to organization secrets, or someone creates a PR from a fork (which has the same issue).
However, this didn't seem to work for forks (as tested in #177) so I tried changing the way that we check for permissions to instead simply assign the secret to an env var and then check that in the relevant actions.
This PR is to ensure actions work as intended when created from the main repo.
I believe this behavior is triggered by the way in which the action checks permissions. If I don't misread the code, it checks whether the user (owner of the forked repo I assume?) has permissions on the main repo. Since my owner …
=> Change permissions check to only publish artifacts when a PR is created from the same repo, not from a fork

docs/modules/ROOT/pages/usage.adoc
Adjusted based on inspecting https://github.com/stackabletech/zookeeper-operator/blob/main/deploy/crd/zookeepercluster.crd.yaml and that https://github.com/stackabletech/zookeeper-operator/blob/main/examples/simple-zookeepercluster.yaml works. 
Otherwise, get:
```
error: error validating "STDIN": error validating data: [ValidationError(ZookeeperCluster.spec.servers.roleGroups.config): unknown field "metricsPort" in tech.stackable.zookeeper.v1alpha1.ZookeeperCluster.spec.servers.roleGroups, ValidationError(ZookeeperCluster.spec.servers.roleGroups.config): missing required field "selector" in tech.stackable.zookeeper.v1alpha1.ZookeeperCluster.spec.servers.roleGroups, ValidationError(ZookeeperCluster.spec.servers.roleGroups.replicas): invalid type for …
```
=> Adjust example ZookeeperCluster to adhere to CRD

rust/operator-binary/src/discovery.rs
=> `nodeport_hosts`: use provided `port_name` when trying to find `ServicePort`

CHANGELOG.md, rust/operator-binary/src/main.rs
This should make restarts *much* faster, and try to ensure that we don't shut
down in the middle of a reconciliation.
=> Shut down gracefully on termination signals

CHANGELOG.md, rust/operator-binary/src/zk_controller.rs
This is required since some CSI providers only make the volume folder
accessible to root by default.
=> Chown data folder on startup

CHANGELOG.md, deploy/config-spec/properties.yaml, deploy/helm/zookeeper-operator/configs/properties.yaml, docs/modules/zookeeper/pages/usage_guide/configuration_environment_overrides.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/zk_controller.rs
Make JVM security settings related to the DNS cache configurable with configOverrides.
Tested manually that when caching negative results for 5 minutes, the quorum is not reached.
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/63/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> JVM config overrides

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/zookeeper-operator/crds/crds.yaml, docs/modules/zookeeper/pages/usage_guide/operations/graceful-shutdown.adoc, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/operations/graceful_shutdown.rs, rust/operator-binary/src/operations/mod.rs, rust/operator-binary/src/zk_controller.rs, tests/templates/kuttl/smoke/10-assert.yaml.j2
Part of https://github.com/stackabletech/issues/issues/357
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support graceful shutdown

docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, docs/modules/zookeeper/examples/getting_started/code/install_output.txt, docs/modules/zookeeper/examples/getting_started/code/install_output.txt.j2, docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2, docs/modules/zookeeper/pages/index.adoc, docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
Add changes from https://github.com/stackabletech/zookeeper-operator/commit/9d394bbb79bd89e80cc8ad56dd631dde0544950c#diff-b22263413919527a13ab1db697e5ea76d2541ed5a5be96fb903bbb8529c63c1b to the template file.
```[tasklist]
```
```[tasklist]
```
=> docs: Add listener-operator where missing

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/zookeeper-operator/crds/crds.yaml, rust/crd/src/affinity.rs, rust/crd/src/authentication.rs, rust/crd/src/lib.rs, rust/crd/src/security.rs, rust/operator-binary/src/discovery.rs, rust/operator-binary/src/utils.rs, rust/operator-binary/src/zk_controller.rs
- **BREAKING** Removed legacy node selector on roleGroups.
- Use new label builders.
- Use explicit match arms for AuthorizationClassProvider ([as discussed](https://github.com/stackabletech/airflow-operator/pull/364#discussion_r1436810693))
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: bump operator-rs to 0.60.1

CHANGELOG.md, Cargo.lock, rust/crd/src/authentication.rs, rust/crd/src/security.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/zk_controller.rs
Fixes https://github.com/stackabletech/zookeeper-operator/issues/761
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> configOverrides are now able to overwrite configs written by the operator

docs/modules/zookeeper/pages/index.adoc, docs/modules/zookeeper/pages/znodes.adoc
fixes #759 
```[tasklist]
```
```[tasklist]
```
=> docs: ZNode management requires connectivity between the operator and the ZookeeperCluster

CHANGELOG.md, docs/modules/zookeeper/partials/supported-versions.adoc, tests/test-definition.yaml
Add Zookeeper 3.8.4 as LTS.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Zookeeper 3.8.4 as LTS

CHANGELOG.md, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml, docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2, docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-authentication.yaml, docs/modules/zookeeper/examples/usage_guide/example-cluster-tls-encryption.yaml, docs/modules/zookeeper/pages/reference/discovery.adoc, docs/modules/zookeeper/pages/usage_guide/configuration_environment_overrides.adoc, docs/modules/zookeeper/pages/znodes.adoc, docs/modules/zookeeper/partials/supported-versions.adoc, examples/simple-zookeeper-tls-cluster.yaml, rust/crd/src/affinity.rs, rust/crd/src/lib.rs, rust/operator-binary/src/zk_controller.rs, tests/test-definition.yaml
This reverts commit 743f5054c09da803115e35e83ba2a64589ed8440 to roll back Zookeeper to 3.9.1 (undoing #784).
See https://github.com/stackabletech/docker-images/pull/595
=> revert: zookeeper 3.9.2

docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, docs/modules/zookeeper/examples/getting_started/code/install_output.txt, docs/modules/zookeeper/examples/getting_started/code/install_output.txt.j2
=> docs(getting-started): update stackablectl op install output

CHANGELOG.md, docs/modules/zookeeper/partials/supported-versions.adoc, tests/test-definition.yaml
Part of stackabletech/docker-images#832.
```[tasklist]
```
```[tasklist]
```
=> chore: Remove ZooKeeper 3.8.4 from tests and docs

tests/templates/kuttl/cluster-operation/10-install-zookeeper.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-zookeeper.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-zookeeper.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-zookeeper.yaml.j2, tests/templates/kuttl/delete-rolegroup/05-install-zookeeper.yaml.j2, tests/templates/kuttl/delete-rolegroup/10-remove-secondary.yaml.j2, tests/templates/kuttl/logging/11-install-zookeeper.yaml.j2, tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2, tests/templates/kuttl/znode/10-install-zookeeper.yaml.j2, tests/test-definition.yaml
=> Allow custom images in tests

CHANGELOG.md, rust/operator-binary/src/main.rs, rust/operator-binary/src/zk_controller.rs, rust/operator-binary/src/znode_controller.rs
Part of stackabletech/issues#211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Migrate to DeserializeGuard

docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/zookeeper-operator/pull/887.
=> chore(getting_started): Replace templating instructions with make

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/zk_controller.rs
Some minor changes needed to remove dependency on now private fn in op-rs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Patch op-rs version to use one that fixes SUP-148.

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, Makefile, crate-hashes.json, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, rust/operator-binary/src/zk_controller.rs
Add the following PRs to the release 24.11:
* #885 
* #887 
* #889
=> Update release branch

tests/templates/kuttl/smoke/10-assert.yaml.j2, tests/templates/kuttl/smoke/12-assert.yaml
Followup to #881, part of https://github.com/stackabletech/issues/issues/527
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(test): factor out containerdebug test and reduce noise

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/zookeeper-operator/crds/crds.yaml, deploy/helm/zookeeper-operator/values.yaml, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, docs/modules/zookeeper/pages/reference/environment-variables.adoc, tests/templates/kuttl/logging/20-install-check.yaml, tests/templates/kuttl/smoke/20-install-check.yaml, tests/test-definition.yaml
Openshift tests:
```
--- PASS: kuttl (266.91s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/znode_zookeeper-latest-3.9.2_openshift-true (43.55s)
--- PASS: kuttl/harness/logging_zookeeper-3.9.2_openshift-true (82.56s)
--- PASS: kuttl/harness/cluster-operation_zookeeper-latest-3.9.2_openshift-true (59.73s)
--- PASS: kuttl/harness/delete-rolegroup_zookeeper-3.9.2_openshift-true (92.59s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-true_use-client-auth-tls-true_openshift-true (175.48s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: add oci references, merge templating changes

CHANGELOG.md, docs/modules/zookeeper/partials/supported-versions.adoc, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1083.
- Remove ZooKeeper 2.9.2 from tests and docs
=> chore: Remove ZooKeeper 3.9.2

CHANGELOG.md, tests/templates/kuttl/logging/05-install-zookeeper-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
=> test: Bump vector to 0.46.1

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/crd/authentication.rs, rust/operator-binary/src/crd/security.rs, rust/operator-binary/src/zk_controller.rs
Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.0 which versions common CRD structs.
=> chore: Bump stackable_operator to 0.93.1

CHANGELOG.md, rust/operator-binary/src/zk_controller.rs
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
=> chore: Remove hardcoded uid and gid

CHANGELOG.md, docs/modules/zookeeper/pages/usage_guide/monitoring.adoc, rust/operator-binary/src/config/jvm.rs, rust/operator-binary/src/crd/mod.rs, rust/operator-binary/src/zk_controller.rs, tests/templates/kuttl/smoke/test_zookeeper.py
Part of https://github.com/stackabletech/zookeeper-operator/issues/954
Docs added here: https://docs.stackable.tech/home/nightly/zookeeper/usage_guide/monitoring/
```
--- PASS: kuttl (292.82s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/cluster-operation_zookeeper-latest-3.9.3_openshift-false (33.82s)
--- PASS: kuttl/harness/znode_zookeeper-latest-3.9.3_openshift-false (28.00s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.3_use-server-tls-false_use-client-auth-tls-false_openshift-false (72.61s)
--- PASS: kuttl/harness/delete-rolegroup_zookeeper-3.9.3_openshift-false (68.26s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.3_use-server-tls-true_use-client-auth-tls-true_openshift-false (136.65s)
--- PASS: kuttl/harness/logging_zookeeper-3.9.3_openshift-false (68.04s)
--- PASS: …
```
=> chore: add built-in Prometheus support

docs/modules/zookeeper/examples/getting_started/code/getting_started.sh, docs/modules/zookeeper/examples/getting_started/code/getting_started.sh.j2, docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml, docs/modules/zookeeper/examples/getting_started/code/zookeeper.yaml.j2
- Move `listenerClass` to under roleConfig.
- Move to `cluster-internal` listener class.
- Update the service name (no longer at the rolegroup level)
Part of <https://github.com/stackabletech/issues/issues/742>
> [!NOTE]
> During a Stackable release we need to check (and optionally update) the
> getting-started scripts to ensure they still work after product and operator
> updates.
```shell
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
popd
```
=> fix(docs): Update getting-started script pre-25.7.0

Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/config/jvm.rs, rust/operator-binary/src/crd/mod.rs, rust/operator-binary/src/crd/security.rs, rust/operator-binary/src/discovery.rs, rust/operator-binary/src/listener.rs, rust/operator-binary/src/main.rs, rust/operator-binary/src/product_logging.rs, rust/operator-binary/src/zk_controller.rs, rust/operator-binary/src/znode_controller.rs
Part of https://github.com/stackabletech/issues/issues/762
=> chore: Update to stackable-operator 0.95.0
